#!/bin/sh

##
# aws-elasticbeanstalk-describe-health
#
# Syntax:
#
#     aws-elasticbeanstalk-describe-health
#
# Example:
#
#     $ aws-elasticbeanstalk-describe-health
#     ... lots of sections of JSON responses ...
#
# This queries Amazon Web Service (AWS) Elastic Beanstalk (EB)
# for environment health and instances health, and prints results.
#
# This script is based on AWS EB documentation as of 2018-12-01.
##

# https://github.com/SixArm/sixarm-unix-shell-functions
out() { printf %s\\n "$*" ; }
err() { >&2 printf %s\\n "$*" ; }
die() { >&2 printf %s\\n "$*" ; exit 1 ; }
big() { printf \\n###\\n#\\n#\ %s\\n#\\n###\\n\\n "$*"; }
cmd() { command -v $1 >/dev/null 2>&1 ; }

preflight(){
  cmd aws || die "Command 'aws' is missing; try https://aws.amazon.com/cli/"
  cmd jq || die "Command 'jq' is missing; try https://stedolan.github.io/jq/"
}

do_environments(){
  for name in $(aws elasticbeanstalk describe-environments | jq -r '.Environments[].EnvironmentName'); do
    do_environment $name 
  done
}

do_environment(){
  big "Environment:$name - Environment Health"
  aws elasticbeanstalk describe-environment-health --environment-name "$name" --attribute-names All
  big "Environment:$name - Instances Health"
  aws elasticbeanstalk describe-instances-health --environment-name "$name" --attribute-names All
}

main(){
  big "AWS Elastic Beanstalk - describe health - profile $AWS_PROFILE"
  preflight
  do_environments
}

main
