#!/bin/sh

##
# aws-elasticbeanstalk-describe-health
#
# Syntax:
#
#     aws-elasticbeanstalk-describe-health
#
# Example:
#
#     $ aws-elasticbeanstalk-describe-health
#     ... lots of sections of JSON responses ...
#
# This queries Amazon Web Service (AWS) Elastic Beanstalk (EB)
# for environment health and instances health, and prints results.
#
# This script is based on AWS EB documentation as of 2018-12-01.
##

# # Include https://github.com/SixArm/posix-shell-script-kit
. "$(dirname "$(readlink -f "$0")")/posix-shell-script-kit"

preflight(){
  command_exists_or_die aws
  command_exists_or_die jq
}

do_environments(){
  for name in $(aws elasticbeanstalk describe-environments | jq -r '.Environments[].EnvironmentName'); do
    do_environment $name 
  done
}

do_environment(){
  big "Environment:$name - Environment Health"
  aws elasticbeanstalk describe-environment-health --environment-name "$name" --attribute-names All
  big "Environment:$name - Instances Health"
  aws elasticbeanstalk describe-instances-health --environment-name "$name" --attribute-names All
}

main(){
  big "AWS Elastic Beanstalk - describe health - profile $AWS_PROFILE"
  preflight
  do_environments
}

main
