#!/bin/sh
set -euf

##
# aws-elasticbeanstalk-describe-everything
#
# Syntax:
#
#     aws-elasticbeanstalk-describe-everythin
#
# Example:
#
#     $ aws-elasticbeanstalk-describe-everything
#     ... lots of sections of JSON responses ...
#
# This queries Amazon Web Service (AWS) Elastic Beanstalk (EB)
# for everything that's available about the profile's beanstalk:
#
#   * Applications
#   * Application versions
#   * Environments
#   * Platforms
#   * Account attributes
#
# This script is based on AWS EB documentation as of 2018-12-01.
##

# # Include https://github.com/SixArm/posix-shell-script-kit
. "$(dirname "$(readlink -f "$0")")/posix-shell-script-kit"

preflight(){
  command_exists_or_die aws
  command_exists_or_die jq
}

do_beanstalk(){
  big "Applications"
  aws --profile "$AWS_PROFILE" elasticbeanstalk describe-applications

  big "Application Versions"
  aws elasticbeanstalk describe-application-versions

  big "Environments"
  aws elasticbeanstalk describe-environments

  big "Platforms"
  aws elasticbeanstalk describe-environments |
  jq -r '[.Environments[].PlatformArn] | unique[]'

  big "Account Attributes"
  aws elasticbeanstalk describe-account-attributes

  big "Events"
  aws elasticbeanstalk describe-events
}

do_environments(){
  for name in $(aws elasticbeanstalk describe-environments | jq -r '.Environments[].EnvironmentName'); do
    do_environment $name 
  done
}
  
do_environment(){
  name="$1"
  big "Environment:$name - Environment Health"
  aws elasticbeanstalk describe-environment-health --environment-name "$name" --attribute-names All

  big "Environment:$name - Instances Health"
  aws elasticbeanstalk describe-instances-health --environment-name "$name" --attribute-names All

  big "Environment:$name - Environment Resources" 
  aws elasticbeanstalk describe-environment-resources --environment-name "$name"

  big "Environment:$name - Environment Managed Actions"
  aws elasticbeanstalk describe-environment-managed-actions --environment-name "$name"
 
  big "Environment:$name - Environment Managed Action History - max items 10"
  aws elasticbeanstalk describe-environment-managed-action-history --environment-name "$name" --max-items 10
}

do_platforms(){
  for name in $(aws elasticbeanstalk describe-environments | jq -r '[.Environments[].PlatformArn] | unique[]'); do
    do_platform $name
  done
}

do_platform(){
  name="$1"
  big "Platform:$name - Platform Version"
  aws elasticbeanstalk describe-platform-version --platform-arn "$name"
}

do_applications(){
  for name in $(aws elasticbeanstalk describe-applications | jq -r '.Applications[].ApplicationName'); do 
    do_application $name
  done
}

do_application(){
  name="$1"
  big "Application:$name - Application Version"
  aws elasticbeanstalk describe-application-versions --application-name "$name"
}

main(){
  preflight
  big "AWS Elastic Beanstalk - describe everything - profile $AWS_PROFILE"
  do_beanstalk
  do_environments
  do_platforms
  do_applications
}

main
